receivers:
  github:
    initial_delay: 1s
    collection_interval: 60s
    scrapers:
      scraper:
        metrics:
          vcs.change.count:
            enabled: false
          vcs.change.duration:
            enabled: false
          vcs.change.time_to_approval:
            enabled: false
          vcs.change.time_to_merge:
            enabled: false
          vcs.ref.count:
            enabled: false
          vcs.ref.lines_delta:
            enabled: false
          vcs.ref.revisions_delta:
            enabled: false
          vcs.ref.time:
            enabled: false
          vcs.repository.count:
            enabled: false
          vcs.contributor.count:
            enabled: true
        github_org: open-telemetry
        concurrency_limit: 50 # Optional: (default: 50)
        merged_pr_lookback_days: 30 # Optional: (default: 30)
        auth:
          authenticator: bearertokenauth/github

exporters:
  js:
  debug:
    verbosity: detailed

service:
  extensions: [bearertokenauth/github]
  pipelines:
    metrics:
      receivers: [github]
      exporters: [js, debug]
  telemetry:
    traces:
      level: none
    metrics:
      level: none
      readers: []
