receivers:
  js:

processors:
  deltatorate:
    metrics:
      - click.count
  transform:
    metric_statements:
      - set(metric.name, "click.rate")
      - set(metric.description, "Number of clicks per second")
      - set(metric.unit, "{click}/s")

exporters:
  js:
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [js]
      processors: [deltatorate, transform]
      exporters: [js, debug]
  telemetry:
    traces:
      level: none
    metrics:
      level: none
      readers: []
