receivers:
  js:

exporters:
  js:
  debug:

service:
  pipelines:
    metrics:
      receivers: [js]
      exporters: [js, debug]
  telemetry:
    traces:
      level: none
    metrics:
      level: none
      readers: []
